In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
shape = (5, 3)

x_empty = torch.empty(*shape)
print("Uninitialized tensor:")
print(x_empty)

x_rand = torch.rand(*shape)
print("Randomly initialized tensor:")
print(x_rand)

x_zero = torch.zeros(*shape, dtype=torch.long)
print("long zero filled tensor:")
print(x_zero)

Uninitialized tensor:
tensor([[1.1138e-10, 4.5792e-41, 1.1138e-10],
        [4.5792e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [5.8253e-10, 1.7569e-04, 1.1351e-43]])
Randomly initialized tensor:
tensor([[0.4299, 0.1654, 0.2162],
        [0.6907, 0.8115, 0.8159],
        [0.6067, 0.0040, 0.9603],
        [0.6863, 0.5061, 0.5364],
        [0.3616, 0.8123, 0.7404]])
long zero filled tensor:
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
# construct from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

# size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.5095, -1.4986,  0.2416],
        [ 0.0731, -1.0399, -0.4979],
        [ 1.3446, -0.0501,  0.2753],
        [-0.0297,  0.6203,  1.4888],
        [ 0.0379, -0.9571,  0.6414]])
torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

## Operations
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

In [6]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5891, -1.0372,  1.1268],
        [ 0.8012, -0.4696,  0.2498],
        [ 2.1289,  0.0203,  1.1044],
        [ 0.6008,  1.5970,  1.6485],
        [ 0.1205, -0.8812,  0.9374]])


Addition: syntax 2



In [7]:
print(torch.add(x, y))

tensor([[ 1.5891, -1.0372,  1.1268],
        [ 0.8012, -0.4696,  0.2498],
        [ 2.1289,  0.0203,  1.1044],
        [ 0.6008,  1.5970,  1.6485],
        [ 0.1205, -0.8812,  0.9374]])


Addition: providing an output tensor as argument



In [8]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5891, -1.0372,  1.1268],
        [ 0.8012, -0.4696,  0.2498],
        [ 2.1289,  0.0203,  1.1044],
        [ 0.6008,  1.5970,  1.6485],
        [ 0.1205, -0.8812,  0.9374]])


Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)

# note that y is mutated

tensor([[ 1.5891, -1.0372,  1.1268],
        [ 0.8012, -0.4696,  0.2498],
        [ 2.1289,  0.0203,  1.1044],
        [ 0.6008,  1.5970,  1.6485],
        [ 0.1205, -0.8812,  0.9374]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [10]:
print(x[:, 1]) # all row, col 1

tensor([-1.4986, -1.0399, -0.0501,  0.6203, -0.9571])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [12]:
x = torch.randn(1)
print(x)
print(x.item())

print(x[0])
print(x[0].item())

tensor([-1.2140])
-1.2139723300933838
tensor(-1.2140)
-1.2139723300933838


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described here:
  https://pytorch.org/docs/torch

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
`tensor.numpy()`


In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [15]:
# a is torch tensor
# b is numpy array

a.add_(2) 
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


Converting NumPy Array to Torch Tensor

Read: Create torch tensor from numpy array: `torch.from_numpy`

In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)
# See how changing the np array changed the Torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [17]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.2140], device='cuda:0')
tensor([-0.2140], dtype=torch.float64)
